version: "3"
services:
  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  typesense:
    image: typesense/typesense:0.22.2
    command: "--data-dir /data --api-key=ecommerce --enable-cors"
    ports:
      - "8108:8108"
    volumes:
      - /typesense-data:/data
  node-app:
    restart: always
    build: .
    image: priyank003/techninja-server
    environment:
      - PORT=8000

volumes:
  typesense-data:
