version: "3"
services:
  nginx:
    ports:
      - "8000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=development
    command: node ./src/server.js
