version: "3"
services:
  nginx:
    ports:
      - "8000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules

    environment:
      - NODE_ENV=development
      - TYPESENSE_KEY=ecommerce
      - MONGO_USER=mongo
      - MONGO_PASSWORD=mongo

    command: npm run dev
